### ISSUE TITLE
[Suggestion] Changing criteria for the extra speech bonus from Look at These

### ISSUE THREAD

**Issue by Jorvalt** [darkconsole/dse-soulgem-oven#21]
Just to make things simpler and add compatibility with mods like The Amazing World of Bikini Armor, I'd suggest changing the extra speech bonus from flashing to just check if an item is equipped in slot 32 (torso). As it stands now most items equipped from that mod will negate the bonus, even if it's not covering the breasts in any way. I assume it's based on tagging but I could be wrong.

**Comment by darkconsole** [comment]
strangely that was how it is suppose to work, just checking slot 32. but because you asked i was looking at it and currently there are no conditions attached at all, suggesting it should always be giving you the exposure bonus even if you had something equipped to that slot.

![image](https://user-images.githubusercontent.com/9095897/123696315-3c2c7900-d821-11eb-8cfc-235104881495.png)

it is normal though that the influences do not kick in until a certain percentage of milk has been produced, just an fyi.

![image](https://user-images.githubusercontent.com/9095897/123696396-55352a00-d821-11eb-95f4-017863653433.png)

**Comment by darkconsole** [comment]
(note: the oldrim mod is more or less as-is, i no longer even have oldrim installed, this is for the sse mod.)

**Comment by Jorvalt** [comment]
Well it's definitely possible to have the bonus not take effect.
Pictured: Character wearing items that have no effect on the bonus
![ScreenShot0](https://user-images.githubusercontent.com/5514973/123798553-e7cedb00-d8ac-11eb-91bc-3f0e86f934fa.png)
And then with a bottom equipped (Slot 52)
![ScreenShot1](https://user-images.githubusercontent.com/5514973/123798577-ebfaf880-d8ac-11eb-9b35-430b5a65e6ae.png)
That's the only thing that's been changed. Breast milk is still at the same state.
This will happen with bottoms, tops (as expected), tassets, abs, and harnesses.

**Comment by Jorvalt** [comment]
I don't know if it's a keyword thing, but I did notice that all of the items that negate the bonus have the ArmorCuirass keyword and all of the ones that dont, don't.

**Comment by darkconsole** [comment]
i suspect that its been so long since i rolled a new release that i might have noticed this and forgot, which might be why the conditions are missing in my copy.

what i am likely to do is do something like "if NotSlot(32) OR HasKeyword(CanSeeThemTiddies)" cuz i wanted to provide a way that those armors that are conveniently missing breast parts to be patched to support this.

**Comment by darkconsole** [comment]
this has been replaced with code that checks for the existence of something on slot 32, putting the actor in a exposed faction. 

additionally this opens the exposure stuff to more than just the milk, including things like dialog conditions.

only works on the player currently, since the influences only work on the player.
