### ISSUE TITLE
[SE] Weird bug with my character's belly

### ISSUE THREAD

**Issue by La-furie-du-Dragon** [darkconsole/dse-soulgem-oven#32]
On Skyrim SE every time the mod updates the gems inside my character, her belly rapidly inflates then deflate to the size it was before updating, I also have Milk Mod Economy and her belly inflates properly from the lactacid, so I guess it comes from the mod.

Also I found some weird thing while browsing the papyrus log, the message "_WARNING: Function dse_sgo_questbody_main..ActorUpdateGems in stack frame 2 in stack 11578 differs from the in-game resource files - using version from save_" repeats hundreds of times with a diffrent number of stack frame every time, could it be what causes my bug ? If yes how could I fix it outside of starting a new save ?

**Comment by darkconsole** [comment]
the error about the function being different sounds like you made a bad choice in trying to upgrade sgo3 to 4, or just one of the beta updates did not go well.

simple way is to literally disable soulgem oven which is 1 checkbox if you use a mod manager, restart the game, resave your save, quit the game, re-enable soulgem oven, load save and go.

when you reload after disabling sgo, because fnis, you'll probably see everyone standing around fucky, and that is fine, they will be unfucky after turning sgo back on.

if you do that it should even still remember who is pregnant and how much they were. as long as you dont use the reset in my mcm the data in storageutil will remain, so sgo picks up where it left off.

that process usually works as that is how i recover my save after destroying it accidentally with a bad line of code lol.

**Comment by La-furie-du-Dragon** [comment]
Ok thanks, I will try and tell you if it works, I didn’t update from sgo 2 or 3, but from the beta 6 to the beta 8

**Comment by La-furie-du-Dragon** [comment]
I tried it and it didn't work, my character wasn't even standing around fucky like when you forget to run fnis and there's still the same message in the papyrus log

**Comment by La-furie-du-Dragon** [comment]
By the way here is a quick but complete [French translation](https://we.tl/t-UxemvMJrw6) with the .txt file from `interface/translations` and the .json file from `configs/translations`.

Also could you make it so we can put up to 15 gems in a character instead of only 12 ? I would love to get 15 gems inside my character instead of 12

**Comment by La-furie-du-Dragon** [comment]
So I didn't realize I had [this mod](https://www.loverslab.com/files/file/23173-soulgem-oven-4-integration-fork/) (warning on LL), while doing what you told me to try in order to fix my game, so it was why no one was standing around fucky, after deactivating it was the case, but after switch both mods back on, nothing changed.
